# Generated by Django 5.1.4 on 2024-12-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_lease_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
