# Generated by Django 5.1.4 on 2024-12-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_delete_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
