# Generated by Django 5.1.3 on 2024-11-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='types',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Commercial', 'Commercial'), ('Land', 'Land')], max_length=10),
        ),
    ]
